"""Static rule specifications for D/E category deterministic checks."""

from __future__ import annotations

# D 类 - 译名规范（40 条）
D_TRANSLATION_SPECS = [
    {
        "rule_id": "D1-101",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["歐巴馬", "欧巴马"],
        "correct": "奧巴馬",
        "description": "美國前總統譯名統一為「奧巴馬」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D1-102",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["柯林頓", "柯林顿", "柯林頓總統"],
        "correct": "克林頓",
        "description": "美國前總統譯名統一為「克林頓」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D1-103",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["希拉蕊"],
        "correct": "希拉里",
        "description": "美國前國務卿譯名統一為「希拉里」。",
        "confidence": 0.95,
    },
    {
        "rule_id": "D1-104",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["梅克爾", "梅克尔"],
        "correct": "默克爾",
        "description": "德國前總理譯名統一為「默克爾」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D1-105",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["薩科奇", "萨科奇"],
        "correct": "薩科齊",
        "description": "法國前總統譯名統一為「薩科齊」。",
        "confidence": 0.97,
    },
    {
        "rule_id": "D1-106",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["馬克宏", "马克宏", "马克龙"],
        "correct": "馬克龍",
        "description": "法國總統譯名統一為「馬克龍」。",
        "confidence": 0.97,
    },
    {
        "rule_id": "D1-107",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["尹錫悦", "尹锡悦"],
        "correct": "尹錫悅",
        "description": "韓國總統譯名統一為「尹錫悅」。",
        "confidence": 0.97,
    },
    {
        "rule_id": "D3-201",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["亞塞拜然", "亚塞拜然"],
        "correct": "阿塞拜疆",
        "description": "國家譯名統一為「阿塞拜疆」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-202",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["巴貝多", "巴贝多"],
        "correct": "巴巴多斯",
        "description": "國家譯名統一為「巴巴多斯」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-203",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["貝里斯", "贝里斯"],
        "correct": "伯利茲",
        "description": "國家譯名統一為「伯利茲」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-204",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["貝南", "贝南"],
        "correct": "貝寧",
        "description": "國家譯名統一為「貝寧」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-205",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["百慕達", "百慕达"],
        "correct": "百慕大",
        "description": "地區譯名統一為「百慕大」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-206",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["波希尼亞及赫塞哥維那", "波希尼亚及赫塞哥维那"],
        "correct": "波黑",
        "description": "國家譯名統一為「波黑」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-207",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["波札那", "波扎那"],
        "correct": "博茨瓦納",
        "description": "國家譯名統一為「博茨瓦納」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-208",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["蒲隆地", "蒲隆地共和國"],
        "correct": "布隆迪",
        "description": "國家譯名統一為「布隆迪」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-209",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["維德角島", "維德角"],
        "correct": "佛得角",
        "description": "國家譯名統一為「佛得角」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-210",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["查德"],
        "correct": "乍得",
        "description": "國家譯名統一為「乍得」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-211",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["科克群島", "科克群岛"],
        "correct": "庫克群島",
        "description": "地區譯名統一為「庫克群島」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-212",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["哥斯大黎加", "哥斯大黎加共和國"],
        "correct": "哥斯達黎加",
        "description": "國家譯名統一為「哥斯達黎加」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-213",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["象牙海岸"],
        "correct": "科特迪瓦",
        "description": "國家譯名統一為「科特迪瓦」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-214",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["克羅埃西亞", "克罗埃西亚"],
        "correct": "克羅地亞",
        "description": "國家譯名統一為「克羅地亞」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-215",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["厄利垂亞", "厄利垂亚"],
        "correct": "厄立特里亞",
        "description": "國家譯名統一為「厄立特里亞」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-216",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["衣索匹亞", "衣索比亚"],
        "correct": "埃塞俄比亞",
        "description": "國家譯名統一為「埃塞俄比亞」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-217",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["加彭"],
        "correct": "加蓬",
        "description": "國家譯名統一為「加蓬」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-218",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["喬治亞", "乔治亚"],
        "correct": "格魯吉亞",
        "description": "國家譯名統一為「格魯吉亞」。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-219",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["迦納", "迦纳"],
        "correct": "加納",
        "description": "國家譯名統一為「加納」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-220",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["格瑞那達", "格瑞那达"],
        "correct": "格林納達",
        "description": "國家譯名統一為「格林納達」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-221",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["瓜地馬拉", "瓜地马拉"],
        "correct": "危地馬拉",
        "description": "國家譯名統一為「危地馬拉」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-222",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["蓋亞那", "盖亚那"],
        "correct": "圭亞那",
        "description": "國家譯名統一為「圭亞那」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-223",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["馬爾地夫", "马尔地夫"],
        "correct": "馬爾代夫",
        "description": "國家譯名統一為「馬爾代夫」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-224",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["馬利", "马利"],
        "correct": "馬里",
        "description": "國家譯名統一為「馬里」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-225",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["茅利塔尼亞", "茅利塔尼亚"],
        "correct": "毛里塔尼亞",
        "description": "國家譯名統一為「毛里塔尼亞」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-226",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["模里西斯", "模里西斯共和國"],
        "correct": "毛里求斯",
        "description": "國家譯名統一為「毛里求斯」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-227",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["諾魯", "诺鲁"],
        "correct": "瑙魯",
        "description": "國家譯名統一為「瑙魯」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-228",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["紐西蘭", "纽西兰"],
        "correct": "新西蘭",
        "description": "國家譯名統一為「新西蘭」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-229",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["尼日"],
        "correct": "尼日爾",
        "description": "國家譯名統一為「尼日爾」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-230",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["奈及利亞", "奈及利亚"],
        "correct": "尼日利亞",
        "description": "國家譯名統一為「尼日利亞」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-231",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["巴布亞紐幾內亞", "巴布亚纽几内亚"],
        "correct": "巴布亞新幾內亞",
        "description": "國家譯名統一為「巴布亞新幾內亞」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-232",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["卡達"],
        "correct": "卡塔爾",
        "description": "國家譯名統一為「卡塔爾」。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-233",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["盧安達", "卢安达"],
        "correct": "盧旺達",
        "description": "國家譯名統一為「盧旺達」。",
        "confidence": 0.99,
    },
]

# E 類 - 特殊規範詞彙（40 條）
E_SPECIAL_SPECS = [
    {
        "rule_id": "E1-101",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（新唐人电视台提供）"],
        "correct": "（新唐人電視台）",
        "description": "圖片來源不需要「提供」字樣，直接保留機構名稱。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-102",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（新唐人電視台提供）"],
        "correct": "（新唐人電視台）",
        "description": "圖片來源不需要「提供」字樣，直接保留機構名稱。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-103",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（大纪元提供）"],
        "correct": "（大紀元）",
        "description": "圖片來源不需要「提供」字樣，直接保留機構名稱。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-104",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（大紀元提供）"],
        "correct": "（大紀元）",
        "description": "圖片來源不需要「提供」字樣，直接保留機構名稱。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-105",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（希望之声提供）"],
        "correct": "（希望之聲）",
        "description": "圖片來源不需要「提供」字樣，直接保留機構名稱。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-106",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（希望之聲提供）"],
        "correct": "（希望之聲）",
        "description": "圖片來源不需要「提供」字樣，直接保留機構名稱。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-107",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（中央社提供）"],
        "correct": "（中央社）",
        "description": "圖片來源不需要「提供」字樣，直接保留機構名稱。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-108",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["／"],
        "correct": "/",
        "description": "圖片來源中的斜線需使用半角「/」。",
        "confidence": 0.9,
    },
    {
        "rule_id": "E1-109",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["摄影："],
        "correct": "",
        "description": "圖說來源不使用「攝影：」前綴。",
        "message": "圖說來源不應包含「攝影：」前綴。",
        "suggestion": "刪除「攝影：」字樣，直接列出攝影者姓名或來源。",
        "can_auto_fix": False,
        "confidence": 0.8,
    },
    {
        "rule_id": "E1-110",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["攝影："],
        "correct": "",
        "description": "圖說來源不使用「攝影：」前綴。",
        "message": "圖說來源不應包含「攝影：」前綴。",
        "suggestion": "刪除「攝影：」字樣，直接列出攝影者姓名或來源。",
        "can_auto_fix": False,
        "confidence": 0.8,
    },
    {
        "rule_id": "E1-111",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["图片来源："],
        "correct": "",
        "description": "圖說中不加「圖片來源：」描述，直接列出來源。",
        "message": "圖說請直接列出版權來源，勿加「圖片來源：」字樣。",
        "suggestion": "移除「圖片來源：」，僅保留機構或攝影者名稱。",
        "can_auto_fix": False,
        "confidence": 0.85,
    },
    {
        "rule_id": "E1-112",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["圖片來源："],
        "correct": "",
        "description": "圖說中不加「圖片來源：」描述，直接列出來源。",
        "message": "圖說請直接列出版權來源，勿加「圖片來源：」字樣。",
        "suggestion": "移除「圖片來源：」，僅保留機構或攝影者名稱。",
        "can_auto_fix": False,
        "confidence": 0.85,
    },
    {
        "rule_id": "E2-201",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["練功"],
        "correct": "煉功",
        "description": "法輪功功法專用字「煉」（不用「練」）。",
        "confidence": 0.96,
    },
    {
        "rule_id": "E2-202",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["练功"],
        "correct": "煉功",
        "description": "法輪功功法專用字「煉」（不用「练」）。",
        "confidence": 0.96,
    },
    {
        "rule_id": "E2-208",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["宏法"],
        "correct": "弘法",
        "description": "法輪功相關用語統一為「弘法」。",
        "confidence": 0.94,
    },
    {
        "rule_id": "E2-209",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["七．二○", "七·二○", "七·二〇", "七二○"],
        "correct": "7·20",
        "description": "法輪功關鍵日期統一寫作「7·20」。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E2-210",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["四二五", "四．二五", "四·二五"],
        "correct": "4·25",
        "description": "法輪功關鍵日期統一寫作「4·25」。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E3-301",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["89年"],
        "correct": "",
        "description": "年代需寫全稱（如1989年或民國78年）。",
        "message": "請將「89年」補全為具體年份（如1989年或民國78年）。",
        "suggestion": "根據語境補全「89年」的具體年份，避免僅用兩位數字。",
        "can_auto_fix": False,
        "confidence": 0.7,
    },
    {
        "rule_id": "E3-302",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["六四事件"],
        "correct": "六四天安門事件",
        "description": "歷史事件需寫全稱「六四天安門事件」。",
        "confidence": 0.96,
    },
    {
        "rule_id": "E3-304",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["文革"],
        "correct": "文化大革命",
        "description": "歷史事件需寫全稱「文化大革命」。",
        "confidence": 0.94,
    },
    {
        "rule_id": "E3-307",
        "category": "E",
        "subcategory": "E3",
        "patterns": [
            {"value": r"公元前\d+—\d+", "regex": True},
        ],
        "correct": "",
        "description": "公元前紀年需在兩個年份前都保留「前」字。",
        "message": "公元前紀年格式應為「公元前236—前183」等形式。",
        "suggestion": "在第二個年份前補上「前」，確保格式為「公元前X—前Y」。",
        "can_auto_fix": False,
        "confidence": 0.85,
    },
    {
        "rule_id": "E4-401",
        "category": "E",
        "subcategory": "E4",
        "patterns": [
            {"value": r"covid[-\s]?19", "regex": True, "ignore_case": True},
        ],
        "correct": "COVID-19",
        "description": "疫情名稱統一寫作大寫「COVID-19」。",
        "confidence": 0.96,
    },
    {
        "rule_id": "E4-402",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["Delta变种", "Delta变種", "Delta 变种"],
        "correct": "Delta變種",
        "description": "病毒變種名稱統一寫作「Delta變種」。",
        "confidence": 0.92,
    },
    {
        "rule_id": "E4-403",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["Omicron变种", "Omicron变種", "Omicron 变种"],
        "correct": "Omicron變種",
        "description": "病毒變種名稱統一寫作「Omicron變種」。",
        "confidence": 0.92,
    },
    {
        "rule_id": "E4-404",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["youtube", "Youtube", "YOUTUBE"],
        "correct": "YouTube",
        "description": "品牌名稱統一寫作「YouTube」。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-405",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["youtuber", "Youtuber", "YOUTUBER"],
        "correct": "YouTuber",
        "description": "內容創作者稱謂統一寫作「YouTuber」。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-406",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["facebook", "FaceBook", "FACEBOOK"],
        "correct": "Facebook",
        "description": "品牌名稱統一寫作「Facebook」。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-407",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["instagram", "INSTAGRAM"],
        "correct": "Instagram",
        "description": "品牌名稱首字母大寫，其餘小寫「Instagram」。",
        "confidence": 0.92,
    },
    {
        "rule_id": "E4-408",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["whatsapp", "Whatsapp", "WHATSAPP"],
        "correct": "WhatsApp",
        "description": "通訊應用名稱統一寫作「WhatsApp」。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-409",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["tiktok", "Tik tok", "Tik-tok", "Tiktok"],
        "correct": "TikTok",
        "description": "短影音平台名稱統一寫作「TikTok」。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-410",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["telegram", "TELEGRAM"],
        "correct": "Telegram",
        "description": "通訊應用名稱統一寫作「Telegram」。",
        "confidence": 0.92,
    },
]

# A4 类 - 非正式用语（30 条扩展规则）
# 注：包含 A4-001 到 A4-030，InformalLanguageRule (A4-014) 已被字典规则覆盖
A4_INFORMAL_SPECS = [
    # A4-001 到 A4-010: 网络流行语和新词
    {
        "rule_id": "A4-001",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["给力", "不给力"],
        "correct": None,
        "description": "网络流行语，正式文章中不宜使用",
        "confidence": 0.90,
    },
    {
        "rule_id": "A4-002",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["高大上"],
        "correct": None,
        "description": "网络流行语，正式文章中不宜使用",
        "confidence": 0.92,
    },
    {
        "rule_id": "A4-003",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["秒杀"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.88,
    },
    {
        "rule_id": "A4-004",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["逆袭"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-005",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["脑洞", "脑洞大开"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.90,
    },
    {
        "rule_id": "A4-006",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["吐槽"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.88,
    },
    {
        "rule_id": "A4-007",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["点赞"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-008",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["杠精"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.95,
    },
    {
        "rule_id": "A4-009",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["抄作业"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.87,
    },
    {
        "rule_id": "A4-010",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["神器"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.83,
    },
    # A4-011 到 A4-015: 口语化表达
    {
        "rule_id": "A4-011",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["挺好的", "挺不错", "挺棒"],
        "correct": None,
        "description": "口语化表达，正式文章中不宜使用",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-012",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["超级棒", "超级好", "超级赞"],
        "correct": None,
        "description": "口语化表达，正式文章中不宜使用",
        "confidence": 0.88,
    },
    {
        "rule_id": "A4-013",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["蛮好", "蛮不错"],
        "correct": None,
        "description": "口语化表达，正式文章中不宜使用",
        "confidence": 0.87,
    },
    {
        "rule_id": "A4-015",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["有点儿", "一点儿"],
        "correct": None,
        "description": "口语化表达，建议使用有些或略微",
        "confidence": 0.75,
    },
    # A4-016 到 A4-020: 不规范缩写和简称
    {
        "rule_id": "A4-016",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["辆车", "几辆车"],
        "correct": None,
        "description": "口语化量词，建议使用完整表达",
        "confidence": 0.70,
    },
    {
        "rule_id": "A4-017",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["个人", "几个人"],
        "correct": None,
        "description": "统计数据中建议使用名或位",
        "confidence": 0.65,
    },
    {
        "rule_id": "A4-018",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["蛮多", "好多", "老多"],
        "correct": None,
        "description": "口语化数量词，不适合正式文章",
        "confidence": 0.88,
    },
    {
        "rule_id": "A4-019",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["好几个", "好几次", "好几天"],
        "correct": None,
        "description": "口语化表达，建议替换为更正式的表达",
        "confidence": 0.80,
    },
    {
        "rule_id": "A4-020",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["差不多"],
        "correct": None,
        "description": "口语化表达，建议使用更精确的表达",
        "confidence": 0.82,
    },
    # A4-021 到 A4-025: 语气词和感叹词
    {
        "rule_id": "A4-021",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["哇", "哇塞", "哇哦"],
        "correct": None,
        "description": "感叹词，正式文章中不宜使用",
        "confidence": 0.92,
    },
    {
        "rule_id": "A4-022",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["哈哈", "嘿嘿", "呵呵"],
        "correct": None,
        "description": "拟声笑词，正式文章中不宜使用",
        "confidence": 0.95,
    },
    {
        "rule_id": "A4-023",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["啦", "咯", "喽", "嘛"],
        "correct": None,
        "description": "语气助词，正式文章中应谨慎使用",
        "confidence": 0.75,
    },
    {
        "rule_id": "A4-024",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["呀", "哟", "嘞"],
        "correct": None,
        "description": "口语化语气词，正式文章中不宜使用",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-025",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["喔", "哦"],
        "correct": None,
        "description": "语气词，正式文章中应谨慎使用",
        "confidence": 0.70,
    },
    # A4-026 到 A4-029: 其他非正式用语
    {
        "rule_id": "A4-026",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["搞定", "搞"],
        "correct": None,
        "description": "口语化动词，建议使用更精确的表达",
        "confidence": 0.80,
    },
    {
        "rule_id": "A4-027",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["弄好", "弄完", "弄"],
        "correct": None,
        "description": "口语化动词，建议使用更精确的表达",
        "confidence": 0.78,
    },
    {
        "rule_id": "A4-028",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["搞不懂", "弄不明白"],
        "correct": None,
        "description": "口语化表达，建议调整",
        "confidence": 0.82,
    },
    {
        "rule_id": "A4-029",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["挺好玩", "好玩儿"],
        "correct": None,
        "description": "口语化表达，建议替换为更正式的表达",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-030",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["小伙伴", "小伙伴们"],
        "correct": None,
        "description": "网络流行称呼，正式文章中建议使用正式称谓",
        "confidence": 0.80,
    },
]

# E2 類 - 法輪功相關術語擴展規則（補充）
E2_FALUN_GONG_EXTENDED_SPECS = [
    {
        "rule_id": "E2-203",
        "category": "E",
        "subcategory": "E2",
        "patterns": [
            {"value": r"法輪功.{0,10}它", "regex": True},
            {"value": r"法轮功.{0,10}它", "regex": True},
            {"value": r"法輪大法.{0,10}它", "regex": True},
            {"value": r"法轮大法.{0,10}它", "regex": True},
        ],
        "correct": None,
        "description": "指代法輪功時應使用「他」而非「它」，體現尊重。",
        "message": "法輪功代名詞應使用「他」而非「它」。",
        "suggestion": "將「它」改為「他」。",
        "can_auto_fix": False,
        "confidence": 0.85,
    },
    {
        "rule_id": "E2-204",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["法輪功練習者", "法轮功练习者"],
        "correct": "法輪功學員",
        "description": "法輪功修煉者統一稱為「學員」，不用「練習者」。",
        "confidence": 0.90,
    },
    {
        "rule_id": "E2-205",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["大法徒弟", "法輪功徒弟", "法轮功徒弟"],
        "correct": "大法弟子",
        "description": "統一使用「大法弟子」稱呼。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E2-206",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["退黨退團退隊", "退党退团退队"],
        "correct": None,
        "description": "三退首次出現時需解釋：退黨、退團、退隊。",
        "message": "「三退」首次出現時應解釋其含義。",
        "suggestion": "改為「三退（退黨、退團、退隊）」。",
        "can_auto_fix": False,
        "confidence": 0.80,
    },
    {
        "rule_id": "E2-211",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["鎮壓法輪功", "镇压法轮功"],
        "correct": "迫害法輪功",
        "description": "應使用「迫害」而非「鎮壓」描述中共對法輪功的行為。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E2-212",
        "category": "E",
        "subcategory": "E2",
        "patterns": [
            {"value": r"法輪功.{0,5}邪教", "regex": True},
            {"value": r"法轮功.{0,5}邪教", "regex": True},
        ],
        "correct": None,
        "description": "法輪功不是邪教，禁止使用此類表述。",
        "message": "法輪功不是邪教，請刪除或修正此表述。",
        "suggestion": "刪除「邪教」相關表述，使用客觀中立的描述。",
        "severity": "critical",
        "blocks_publish": True,
        "can_auto_fix": False,
        "confidence": 0.99,
    },
    {
        "rule_id": "E2-213",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["煉習", "炼习"],
        "correct": None,
        "description": "修煉用「煉」，體育鍛煉用「練」，不可混用。",
        "message": "「煉」用於修煉，「練」用於體育鍛煉，請確認使用正確。",
        "can_auto_fix": False,
        "confidence": 0.70,
    },
    {
        "rule_id": "E2-214",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["法輪功組織", "法轮功组织"],
        "correct": None,
        "description": "法輪功是鬆散的修煉群體，不是「組織」。",
        "message": "法輪功沒有組織形式，建議改為「法輪功修煉者」或「法輪功學員」。",
        "suggestion": "改為「法輪功修煉者」或「法輪功學員」。",
        "can_auto_fix": False,
        "confidence": 0.85,
    },
]

# E3 類 - 歷史事件擴展規則（補充）
E3_HISTORICAL_EVENTS_EXTENDED_SPECS = [
    {
        "rule_id": "E3-303",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["反右"],
        "correct": "反右運動",
        "description": "歷史事件需寫全稱「反右運動」。",
        "confidence": 0.90,
    },
    {
        "rule_id": "E3-305",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["大躍進時期", "大跃进时期"],
        "correct": "大躍進運動",
        "description": "歷史事件需寫全稱「大躍進運動」。",
        "confidence": 0.85,
    },
    {
        "rule_id": "E3-306",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["三年困難時期", "三年困难时期", "自然災害時期", "自然灾害时期"],
        "correct": "三年大饑荒",
        "description": "應使用「三年大饑荒」，不用中共美化說法。",
        "confidence": 0.92,
    },
    {
        "rule_id": "E3-307",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["土改"],
        "correct": "土地改革運動",
        "description": "歷史事件需寫全稱「土地改革運動」。",
        "confidence": 0.88,
    },
    {
        "rule_id": "E3-308",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["鎮反", "镇反"],
        "correct": "鎮反運動",
        "description": "歷史事件需寫全稱「鎮反運動」。",
        "confidence": 0.88,
    },
    {
        "rule_id": "E3-309",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["三反五反"],
        "correct": "三反五反運動",
        "description": "歷史事件需寫全稱「三反五反運動」。",
        "confidence": 0.88,
    },
    {
        "rule_id": "E3-310",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["整風", "整风"],
        "correct": "整風運動",
        "description": "歷史事件需寫全稱「整風運動」。",
        "confidence": 0.85,
    },
]

# F4 類 - 黨文化詞彙過濾規則
F4_PARTY_CULTURE_SPECS = [
    {
        "rule_id": "F4-001",
        "category": "F",
        "subcategory": "F4",
        "patterns": [
            {"value": r"(?<!中共)建國(?!前|後|后|初期)", "regex": True},
            {"value": r"(?<!中共)建国(?!前|后|初期)", "regex": True},
        ],
        "correct": "中共建政",
        "description": "「建國」（指1949年）應改為「中共建政」。",
        "message": "「建國」暗示中共代表中國的合法性，應改為「中共建政」。",
        "confidence": 0.85,
    },
    {
        "rule_id": "F4-002",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["國慶節", "国庆节", "國慶日", "国庆日"],
        "correct": "十一",
        "description": "「國慶」（指十一）應改為「十一」，將節日中性化。",
        "confidence": 0.90,
    },
    {
        "rule_id": "F4-003",
        "category": "F",
        "subcategory": "F4",
        "patterns": [
            {"value": r"解放(?:後|后|前|军|战争)", "regex": True},
        ],
        "correct": None,
        "description": "「解放」（指1949年）應根據語境改為「中共奪權」或「易主」。",
        "message": "「解放」帶有中共宣傳色彩，應使用中性表述。",
        "suggestion": "根據語境改為「中共奪權」「易主」或具體年份。",
        "can_auto_fix": False,
        "confidence": 0.80,
    },
    {
        "rule_id": "F4-004",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["春節"],
        "correct": "中國新年",
        "description": "「春節」應改為「中國新年」或「過年」，回歸傳統稱呼。",
        "confidence": 0.75,
    },
    {
        "rule_id": "F4-005",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["農曆", "农历", "陰曆", "阴历"],
        "correct": "黃曆",
        "description": "「農曆/陰曆」應改為「黃曆」，強調傳統文化屬性。",
        "confidence": 0.70,
    },
    {
        "rule_id": "F4-006",
        "category": "F",
        "subcategory": "F4",
        "patterns": [
            {"value": r"國內(?!外)", "regex": True},
            {"value": r"国内(?!外)", "regex": True},
        ],
        "correct": "中國大陸",
        "description": "海外媒體不應稱中國大陸為「國內」，應改為「中國大陸」。",
        "confidence": 0.85,
    },
    {
        "rule_id": "F4-007",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["被和諧", "被和谐"],
        "correct": None,
        "description": "「被和諧」應還原為「被封殺」「被整肅」等真實含義。",
        "message": "「被和諧」是中共網絡審查的委婉說法，應使用準確表述。",
        "suggestion": "改為「被封殺」「被刪除」「被審查」等。",
        "can_auto_fix": False,
        "confidence": 0.90,
    },
    {
        "rule_id": "F4-008",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["新中國", "新中国"],
        "correct": "中共建政後",
        "description": "「新中國」應改為「中共建政後」，否定中共政權的正統性。",
        "confidence": 0.80,
    },
    {
        "rule_id": "F4-009",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["偉大領袖", "伟大领袖"],
        "correct": None,
        "description": "「偉大領袖」等個人崇拜用語應刪除或改為客觀稱呼。",
        "message": "「偉大領袖」屬於中共個人崇拜用語，應使用客觀稱呼。",
        "suggestion": "刪除或改為具體人名。",
        "can_auto_fix": False,
        "confidence": 0.95,
    },
    {
        "rule_id": "F4-010",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["人民政府"],
        "correct": "中共當局",
        "description": "「人民政府」應改為「中共當局」或「中共政權」，還原政權本質。",
        "confidence": 0.85,
    },
    {
        "rule_id": "F4-011",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["反華勢力", "反华势力"],
        "correct": None,
        "description": "「反華勢力」是中共宣傳用語，應使用客觀表述。",
        "message": "「反華勢力」是中共宣傳標籤，應使用客觀中立的表述。",
        "suggestion": "根據語境改為具體描述或刪除。",
        "can_auto_fix": False,
        "confidence": 0.90,
    },
    {
        "rule_id": "F4-012",
        "category": "F",
        "subcategory": "F4",
        "patterns": ["境外勢力", "境外势力"],
        "correct": None,
        "description": "「境外勢力」是中共宣傳用語，應使用客觀表述。",
        "message": "「境外勢力」是中共宣傳標籤，應使用客觀中立的表述。",
        "suggestion": "根據語境改為具體描述或刪除。",
        "can_auto_fix": False,
        "confidence": 0.90,
    },
]
