"""Static rule specifications for D/E category deterministic checks."""

from __future__ import annotations

# D 类 - 译名规范（40 条）
D_TRANSLATION_SPECS = [
    {
        "rule_id": "D1-101",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["歐巴馬", "欧巴马", "奧巴馬"],
        "correct": "奥巴马",
        "description": "美国前总统译名统一为“奥巴马”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D1-102",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["柯林頓", "柯林顿", "柯林頓總統"],
        "correct": "克林顿",
        "description": "美国前总统译名统一为“克林顿”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D1-103",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["希拉蕊"],
        "correct": "希拉里",
        "description": "美国前国务卿译名统一为“希拉里”。",
        "confidence": 0.95,
    },
    {
        "rule_id": "D1-104",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["梅克爾", "梅克尔"],
        "correct": "默克尔",
        "description": "德国前总理译名统一为“默克尔”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D1-105",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["薩科奇", "萨科奇", "薩科齊"],
        "correct": "萨科齐",
        "description": "法国前总统译名统一为“萨科齐”。",
        "confidence": 0.97,
    },
    {
        "rule_id": "D1-106",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["馬克宏", "馬克龍", "马克宏"],
        "correct": "马克龙",
        "description": "法国总统译名统一为“马克龙”。",
        "confidence": 0.97,
    },
    {
        "rule_id": "D1-107",
        "category": "D",
        "subcategory": "D1",
        "patterns": ["尹錫悅", "尹錫悦"],
        "correct": "尹锡悦",
        "description": "韩国总统译名统一为“尹锡悦”。",
        "confidence": 0.97,
    },
    {
        "rule_id": "D3-201",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["亞塞拜然", "亚塞拜然"],
        "correct": "阿塞拜疆",
        "description": "国家译名使用大陆标准“阿塞拜疆”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-202",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["巴貝多", "巴贝多"],
        "correct": "巴巴多斯",
        "description": "国家译名使用大陆标准“巴巴多斯”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-203",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["貝里斯", "贝里斯"],
        "correct": "伯利兹",
        "description": "国家译名使用大陆标准“伯利兹”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-204",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["貝南", "贝南"],
        "correct": "贝宁",
        "description": "国家译名使用大陆标准“贝宁”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-205",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["百慕達", "百慕达"],
        "correct": "百慕大",
        "description": "地区译名使用大陆标准“百慕大”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-206",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["波希尼亞及赫塞哥維那", "波希尼亚及赫塞哥维那"],
        "correct": "波黑",
        "description": "国家译名使用大陆标准“波黑”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-207",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["波札那", "波扎那"],
        "correct": "博茨瓦纳",
        "description": "国家译名使用大陆标准“博茨瓦纳”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-208",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["蒲隆地", "蒲隆地共和國"],
        "correct": "布隆迪",
        "description": "国家译名使用大陆标准“布隆迪”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-209",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["維德角島", "維德角"],
        "correct": "佛得角",
        "description": "国家译名使用大陆标准“佛得角”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-210",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["查德"],
        "correct": "乍得",
        "description": "国家译名使用大陆标准“乍得”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-211",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["科克群島", "科克群岛"],
        "correct": "库克群岛",
        "description": "地区译名使用大陆标准“库克群岛”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-212",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["哥斯大黎加", "哥斯大黎加共和國"],
        "correct": "哥斯达黎加",
        "description": "国家译名使用大陆标准“哥斯达黎加”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-213",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["象牙海岸"],
        "correct": "科特迪瓦",
        "description": "国家译名使用大陆标准“科特迪瓦”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-214",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["克羅埃西亞", "克罗埃西亚"],
        "correct": "克罗地亚",
        "description": "国家译名使用大陆标准“克罗地亚”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-215",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["厄利垂亞", "厄利垂亚"],
        "correct": "厄立特里亚",
        "description": "国家译名使用大陆标准“厄立特里亚”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-216",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["衣索匹亞", "衣索比亚"],
        "correct": "埃塞俄比亚",
        "description": "国家译名使用大陆标准“埃塞俄比亚”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-217",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["加彭"],
        "correct": "加蓬",
        "description": "国家译名使用大陆标准“加蓬”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-218",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["喬治亞", "乔治亚"],
        "correct": "格鲁吉亚",
        "description": "国家译名使用大陆标准“格鲁吉亚”。",
        "confidence": 0.98,
    },
    {
        "rule_id": "D3-219",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["迦納", "迦纳"],
        "correct": "加纳",
        "description": "国家译名使用大陆标准“加纳”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-220",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["格瑞那達", "格瑞那达"],
        "correct": "格林纳达",
        "description": "国家译名使用大陆标准“格林纳达”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-221",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["瓜地馬拉", "瓜地马拉"],
        "correct": "危地马拉",
        "description": "国家译名使用大陆标准“危地马拉”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-222",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["蓋亞那", "盖亚那"],
        "correct": "圭亚那",
        "description": "国家译名使用大陆标准“圭亚那”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-223",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["馬爾地夫", "马尔地夫"],
        "correct": "马尔代夫",
        "description": "国家译名使用大陆标准“马尔代夫”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-224",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["馬利", "马利"],
        "correct": "马里",
        "description": "国家译名使用大陆标准“马里”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-225",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["茅利塔尼亞", "茅利塔尼亚"],
        "correct": "毛里塔尼亚",
        "description": "国家译名使用大陆标准“毛里塔尼亚”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-226",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["模里西斯", "模里西斯共和國"],
        "correct": "毛里求斯",
        "description": "国家译名使用大陆标准“毛里求斯”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-227",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["諾魯", "诺鲁"],
        "correct": "瑙鲁",
        "description": "国家译名使用大陆标准“瑙鲁”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-228",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["紐西蘭", "纽西兰"],
        "correct": "新西兰",
        "description": "国家译名使用大陆标准“新西兰”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-229",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["尼日"],
        "correct": "尼日尔",
        "description": "国家译名使用大陆标准“尼日尔”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-230",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["奈及利亞", "奈及利亚"],
        "correct": "尼日利亚",
        "description": "国家译名使用大陆标准“尼日利亚”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-231",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["巴布亞紐幾內亞", "巴布亚纽几内亚"],
        "correct": "巴布亚新几内亚",
        "description": "国家译名使用大陆标准“巴布亚新几内亚”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-232",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["卡達"],
        "correct": "卡塔尔",
        "description": "国家译名使用大陆标准“卡塔尔”。",
        "confidence": 0.99,
    },
    {
        "rule_id": "D3-233",
        "category": "D",
        "subcategory": "D3",
        "patterns": ["盧安達", "卢安达"],
        "correct": "卢旺达",
        "description": "国家译名使用大陆标准“卢旺达”。",
        "confidence": 0.99,
    },
]

# E 类 - 特殊规范词汇（40 条）
E_SPECIAL_SPECS = [
    {
        "rule_id": "E1-101",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（新唐人电视台提供）"],
        "correct": "（新唐人电视台）",
        "description": "图片来源不需要“提供”字样，直接保留机构名称。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-102",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（新唐人電視台提供）"],
        "correct": "（新唐人电视台）",
        "description": "图片来源不需要“提供”字样，直接保留机构名称。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-103",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（大纪元提供）"],
        "correct": "（大纪元）",
        "description": "图片来源不需要“提供”字样，直接保留机构名称。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-104",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（大紀元提供）"],
        "correct": "（大纪元）",
        "description": "图片来源不需要“提供”字样，直接保留机构名称。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-105",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（希望之声提供）"],
        "correct": "（希望之声）",
        "description": "图片来源不需要“提供”字样，直接保留机构名称。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-106",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（希望之聲提供）"],
        "correct": "（希望之声）",
        "description": "图片来源不需要“提供”字样，直接保留机构名称。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-107",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["（中央社提供）"],
        "correct": "（中央社）",
        "description": "图片来源不需要“提供”字样，直接保留机构名称。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E1-108",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["／"],
        "correct": "/",
        "description": "图片来源中的斜线需使用半角“/”。",
        "confidence": 0.9,
    },
    {
        "rule_id": "E1-109",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["摄影："],
        "correct": "",
        "description": "图说来源不使用“摄影：”前缀。",
        "message": "图说来源不应包含“摄影：”前缀。",
        "suggestion": "删除“摄影：”字样，直接列出摄影者姓名或来源。",
        "can_auto_fix": False,
        "confidence": 0.8,
    },
    {
        "rule_id": "E1-110",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["攝影："],
        "correct": "",
        "description": "图说来源不使用“攝影：”前缀。",
        "message": "图说来源不应包含“攝影：”前缀。",
        "suggestion": "删除“攝影：”字样，直接列出摄影者姓名或来源。",
        "can_auto_fix": False,
        "confidence": 0.8,
    },
    {
        "rule_id": "E1-111",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["图片来源："],
        "correct": "",
        "description": "图说中不加“图片来源：”描述，直接列出来源。",
        "message": "图说请直接列出版权来源，勿加“图片来源：”字样。",
        "suggestion": "移除“图片来源：”，仅保留机构或摄影者名称。",
        "can_auto_fix": False,
        "confidence": 0.85,
    },
    {
        "rule_id": "E1-112",
        "category": "E",
        "subcategory": "E1",
        "patterns": ["圖片來源："],
        "correct": "",
        "description": "图说中不加“圖片來源：”描述，直接列出来源。",
        "message": "图说请直接列出版权来源，勿加“圖片來源：”字样。",
        "suggestion": "移除“圖片來源：”，仅保留机构或摄影者名称。",
        "can_auto_fix": False,
        "confidence": 0.85,
    },
    {
        "rule_id": "E2-201",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["練功"],
        "correct": "煉功",
        "description": "法轮功功法专用字「煉」（不用「練」），保持原文繁简体。",
        "confidence": 0.96,
    },
    {
        "rule_id": "E2-202",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["练功"],
        "correct": "煉功",
        "description": "法轮功功法专用字「煉」（不用「练」），保持原文繁简体。",
        "confidence": 0.96,
    },
    {
        "rule_id": "E2-208",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["宏法"],
        "correct": "弘法",
        "description": "法轮功相关用语统一为“弘法”。",
        "confidence": 0.94,
    },
    {
        "rule_id": "E2-209",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["七．二○", "七·二○", "七·二〇", "七二○"],
        "correct": "7·20",
        "description": "法轮功关键日期统一写作“7·20”。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E2-210",
        "category": "E",
        "subcategory": "E2",
        "patterns": ["四二五", "四．二五", "四·二五"],
        "correct": "4·25",
        "description": "法轮功关键日期统一写作“4·25”。",
        "confidence": 0.95,
    },
    {
        "rule_id": "E3-301",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["89年"],
        "correct": "",
        "description": "年代需写全称（如1989年或民国78年）。",
        "message": "请将“89年”补全为具体年份（如1989年或民国78年）。",
        "suggestion": "根据语境补全“89年”的具体年份，避免仅用两位数字。",
        "can_auto_fix": False,
        "confidence": 0.7,
    },
    {
        "rule_id": "E3-302",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["六四事件"],
        "correct": "六四天安门事件",
        "description": "历史事件需写全称「六四天安门事件」（繁体版使用「六四天安門事件」）。",
        "confidence": 0.96,
    },
    {
        "rule_id": "E3-304",
        "category": "E",
        "subcategory": "E3",
        "patterns": ["文革"],
        "correct": "文化大革命",
        "description": "历史事件需写全称「文化大革命」（繁体版使用「文化大革命」）。",
        "confidence": 0.94,
    },
    {
        "rule_id": "E3-307",
        "category": "E",
        "subcategory": "E3",
        "patterns": [
            {"value": r"公元前\d+—\d+", "regex": True},
        ],
        "correct": "",
        "description": "公元前纪年需在两个年份前都保留“前”字。",
        "message": "公元前纪年格式应为“公元前236—前183”等形式。",
        "suggestion": "在第二个年份前补上“前”，确保格式为“公元前X—前Y”。",
        "can_auto_fix": False,
        "confidence": 0.85,
    },
    {
        "rule_id": "E4-401",
        "category": "E",
        "subcategory": "E4",
        "patterns": [
            {"value": r"covid[-\s]?19", "regex": True, "ignore_case": True},
        ],
        "correct": "COVID-19",
        "description": "疫情名称统一写作大写“COVID-19”。",
        "confidence": 0.96,
    },
    {
        "rule_id": "E4-402",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["Delta變種", "Delta变種", "Delta 變種"],
        "correct": "Delta变种",
        "description": "病毒变种名称统一写作“Delta变种”。",
        "confidence": 0.92,
    },
    {
        "rule_id": "E4-403",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["Omicron變種", "Omicron变種", "Omicron 變種"],
        "correct": "Omicron变种",
        "description": "病毒变种名称统一写作“Omicron变种”。",
        "confidence": 0.92,
    },
    {
        "rule_id": "E4-404",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["youtube", "Youtube", "YOUTUBE"],
        "correct": "YouTube",
        "description": "品牌名称统一写作“YouTube”。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-405",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["youtuber", "Youtuber", "YOUTUBER"],
        "correct": "YouTuber",
        "description": "内容创作者称谓统一写作“YouTuber”。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-406",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["facebook", "FaceBook", "FACEBOOK"],
        "correct": "Facebook",
        "description": "品牌名称统一写作“Facebook”。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-407",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["instagram", "INSTAGRAM"],
        "correct": "Instagram",
        "description": "品牌名称首字母大写，其余小写“Instagram”。",
        "confidence": 0.92,
    },
    {
        "rule_id": "E4-408",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["whatsapp", "Whatsapp", "WHATSAPP"],
        "correct": "WhatsApp",
        "description": "通讯应用名称统一写作“WhatsApp”。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-409",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["tiktok", "Tik tok", "Tik-tok", "Tiktok"],
        "correct": "TikTok",
        "description": "短影音平台名称统一写作“TikTok”。",
        "confidence": 0.93,
    },
    {
        "rule_id": "E4-410",
        "category": "E",
        "subcategory": "E4",
        "patterns": ["telegram", "TELEGRAM"],
        "correct": "Telegram",
        "description": "通讯应用名称统一写作“Telegram”。",
        "confidence": 0.92,
    },
]

# A4 类 - 非正式用语（30 条扩展规则）
# 注：包含 A4-001 到 A4-030，InformalLanguageRule (A4-014) 已被字典规则覆盖
A4_INFORMAL_SPECS = [
    # A4-001 到 A4-010: 网络流行语和新词
    {
        "rule_id": "A4-001",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["给力", "不给力"],
        "correct": None,
        "description": "网络流行语，正式文章中不宜使用",
        "confidence": 0.90,
    },
    {
        "rule_id": "A4-002",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["高大上"],
        "correct": None,
        "description": "网络流行语，正式文章中不宜使用",
        "confidence": 0.92,
    },
    {
        "rule_id": "A4-003",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["秒杀"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.88,
    },
    {
        "rule_id": "A4-004",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["逆袭"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-005",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["脑洞", "脑洞大开"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.90,
    },
    {
        "rule_id": "A4-006",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["吐槽"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.88,
    },
    {
        "rule_id": "A4-007",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["点赞"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-008",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["杠精"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.95,
    },
    {
        "rule_id": "A4-009",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["抄作业"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.87,
    },
    {
        "rule_id": "A4-010",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["神器"],
        "correct": None,
        "description": "网络用语，正式文章中不宜使用",
        "confidence": 0.83,
    },
    # A4-011 到 A4-015: 口语化表达
    {
        "rule_id": "A4-011",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["挺好的", "挺不错", "挺棒"],
        "correct": None,
        "description": "口语化表达，正式文章中不宜使用",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-012",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["超级棒", "超级好", "超级赞"],
        "correct": None,
        "description": "口语化表达，正式文章中不宜使用",
        "confidence": 0.88,
    },
    {
        "rule_id": "A4-013",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["蛮好", "蛮不错"],
        "correct": None,
        "description": "口语化表达，正式文章中不宜使用",
        "confidence": 0.87,
    },
    {
        "rule_id": "A4-015",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["有点儿", "一点儿"],
        "correct": None,
        "description": "口语化表达，建议使用有些或略微",
        "confidence": 0.75,
    },
    # A4-016 到 A4-020: 不规范缩写和简称
    {
        "rule_id": "A4-016",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["辆车", "几辆车"],
        "correct": None,
        "description": "口语化量词，建议使用完整表达",
        "confidence": 0.70,
    },
    {
        "rule_id": "A4-017",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["个人", "几个人"],
        "correct": None,
        "description": "统计数据中建议使用名或位",
        "confidence": 0.65,
    },
    {
        "rule_id": "A4-018",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["蛮多", "好多", "老多"],
        "correct": None,
        "description": "口语化数量词，不适合正式文章",
        "confidence": 0.88,
    },
    {
        "rule_id": "A4-019",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["好几个", "好几次", "好几天"],
        "correct": None,
        "description": "口语化表达，建议替换为更正式的表达",
        "confidence": 0.80,
    },
    {
        "rule_id": "A4-020",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["差不多"],
        "correct": None,
        "description": "口语化表达，建议使用更精确的表达",
        "confidence": 0.82,
    },
    # A4-021 到 A4-025: 语气词和感叹词
    {
        "rule_id": "A4-021",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["哇", "哇塞", "哇哦"],
        "correct": None,
        "description": "感叹词，正式文章中不宜使用",
        "confidence": 0.92,
    },
    {
        "rule_id": "A4-022",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["哈哈", "嘿嘿", "呵呵"],
        "correct": None,
        "description": "拟声笑词，正式文章中不宜使用",
        "confidence": 0.95,
    },
    {
        "rule_id": "A4-023",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["啦", "咯", "喽", "嘛"],
        "correct": None,
        "description": "语气助词，正式文章中应谨慎使用",
        "confidence": 0.75,
    },
    {
        "rule_id": "A4-024",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["呀", "哟", "嘞"],
        "correct": None,
        "description": "口语化语气词，正式文章中不宜使用",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-025",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["喔", "哦"],
        "correct": None,
        "description": "语气词，正式文章中应谨慎使用",
        "confidence": 0.70,
    },
    # A4-026 到 A4-029: 其他非正式用语
    {
        "rule_id": "A4-026",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["搞定", "搞"],
        "correct": None,
        "description": "口语化动词，建议使用更精确的表达",
        "confidence": 0.80,
    },
    {
        "rule_id": "A4-027",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["弄好", "弄完", "弄"],
        "correct": None,
        "description": "口语化动词，建议使用更精确的表达",
        "confidence": 0.78,
    },
    {
        "rule_id": "A4-028",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["搞不懂", "弄不明白"],
        "correct": None,
        "description": "口语化表达，建议调整",
        "confidence": 0.82,
    },
    {
        "rule_id": "A4-029",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["挺好玩", "好玩儿"],
        "correct": None,
        "description": "口语化表达，建议替换为更正式的表达",
        "confidence": 0.85,
    },
    {
        "rule_id": "A4-030",
        "category": "A",
        "subcategory": "A4",
        "patterns": ["小伙伴", "小伙伴们"],
        "correct": None,
        "description": "网络流行称呼，正式文章中建议使用正式称谓",
        "confidence": 0.80,
    },
]
