/**
 * ExcerptReviewSection - Article excerpt/summary editing
 *
 * Phase 11: Moved from PublishPreviewPanel to ParsingReviewPanel
 * - Auto-generate excerpt from article body
 * - AI-powered excerpt optimization
 * - Character count and optimal length guidance
 */

import React, { useState, useCallback } from 'react';
import { Card } from '../ui';
import { Button } from '../ui';
import {
  FileText,
  Sparkles,
  RotateCcw,
  Check,
} from 'lucide-react';

export interface ExcerptReviewSectionProps {
  /** Current excerpt text */
  excerpt: string;
  /** Article body for auto-generation */
  articleBody?: string;
  /** AI suggested excerpt */
  aiSuggestedExcerpt?: string;
  /** Callback when excerpt changes */
  onExcerptChange: (excerpt: string) => void;
  /** Optimal length range [min, max] */
  optimalLength?: [number, number];
  /** Whether AI generation is in progress */
  isGenerating?: boolean;
  /** Callback to trigger AI generation */
  onGenerateExcerpt?: () => void;
  /** Test ID for testing */
  testId?: string;
}

/**
 * ExcerptReviewSection Component
 */
export const ExcerptReviewSection: React.FC<ExcerptReviewSectionProps> = ({
  excerpt,
  articleBody,
  aiSuggestedExcerpt,
  onExcerptChange,
  optimalLength = [100, 200],
  isGenerating = false,
  onGenerateExcerpt,
  testId,
}) => {
  const [selectedSource, setSelectedSource] = useState<'manual' | 'auto' | 'ai'>('manual');

  // Generate excerpt from article body (first 150 chars)
  const autoGeneratedExcerpt = articleBody
    ? articleBody.replace(/<[^>]*>/g, '').substring(0, 150).trim() + '...'
    : '';

  // Get length status
  const getLengthStatus = (length: number): 'good' | 'warning' | 'error' => {
    const [min, max] = optimalLength;
    if (length >= min && length <= max) return 'good';
    if (length >= min - 30 && length <= max + 50) return 'warning';
    return 'error';
  };

  const lengthStatus = getLengthStatus(excerpt.length);
  const statusColors = {
    good: 'text-green-600',
    warning: 'text-amber-600',
    error: 'text-red-600',
  };

  // Handle source selection
  const handleSelectAutoGenerated = () => {
    setSelectedSource('auto');
    onExcerptChange(autoGeneratedExcerpt);
  };

  const handleSelectAiSuggested = () => {
    if (aiSuggestedExcerpt) {
      setSelectedSource('ai');
      onExcerptChange(aiSuggestedExcerpt);
    }
  };

  return (
    <Card className="p-4" data-testid={testId}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-slate-600" />
          <h3 className="font-semibold text-slate-900">文章摘要 (Excerpt)</h3>
        </div>
        <span className={`text-xs ${statusColors[lengthStatus]}`}>
          {excerpt.length}/{optimalLength[0]}-{optimalLength[1]} 字
        </span>
      </div>

      <p className="text-xs text-slate-500 mb-3">
        摘要將顯示在文章列表和搜索結果中
      </p>

      {/* Quick Actions */}
      <div className="flex gap-2 mb-3">
        {autoGeneratedExcerpt && (
          <Button
            variant="outline"
            size="sm"
            onClick={handleSelectAutoGenerated}
            className={selectedSource === 'auto' ? 'ring-2 ring-blue-500' : ''}
          >
            <RotateCcw className="w-3 h-3 mr-1" />
            自動提取
          </Button>
        )}
        {aiSuggestedExcerpt ? (
          <Button
            variant="outline"
            size="sm"
            onClick={handleSelectAiSuggested}
            className={selectedSource === 'ai' ? 'ring-2 ring-purple-500' : ''}
          >
            <Sparkles className="w-3 h-3 mr-1" />
            AI 優化
          </Button>
        ) : onGenerateExcerpt ? (
          <Button
            variant="outline"
            size="sm"
            onClick={onGenerateExcerpt}
            disabled={isGenerating}
          >
            <Sparkles className="w-3 h-3 mr-1" />
            {isGenerating ? '生成中...' : 'AI 生成'}
          </Button>
        ) : null}
      </div>

      {/* AI Suggestion Preview */}
      {aiSuggestedExcerpt && selectedSource !== 'ai' && (
        <div className="mb-3 p-3 bg-purple-50 rounded-lg border border-purple-200">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-4 h-4 text-purple-600" />
            <span className="text-xs font-medium text-purple-700">AI 建議摘要</span>
          </div>
          <p className="text-sm text-purple-900">{aiSuggestedExcerpt}</p>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleSelectAiSuggested}
            className="mt-2 text-purple-600 hover:text-purple-700"
          >
            <Check className="w-3 h-3 mr-1" />
            使用此摘要
          </Button>
        </div>
      )}

      {/* Textarea */}
      <textarea
        value={excerpt}
        onChange={(e) => {
          setSelectedSource('manual');
          onExcerptChange(e.target.value);
        }}
        placeholder="輸入文章摘要..."
        rows={3}
        className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
      />

      {/* Length Guide */}
      <div className="mt-2 flex items-center justify-between text-xs text-slate-500">
        <span>建議長度：{optimalLength[0]}-{optimalLength[1]} 字</span>
        {lengthStatus === 'warning' && (
          <span className="text-amber-600">長度略偏離建議範圍</span>
        )}
        {lengthStatus === 'error' && (
          <span className="text-red-600">長度不符合建議範圍</span>
        )}
      </div>
    </Card>
  );
};

ExcerptReviewSection.displayName = 'ExcerptReviewSection';
