"""Article FAQ model for Phase 7 unified AI optimization."""

from datetime import datetime
from enum import Enum as PyEnum
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    DECIMAL,
    ForeignKey,
    Integer,
    String,
    Text,
    TIMESTAMP,
)
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base

if TYPE_CHECKING:
    from src.models.article import Article


class FAQQuestionType(str, PyEnum):
    """FAQ question type classification."""

    FACTUAL = "factual"  # Fact-based questions
    HOW_TO = "how_to"  # How-to/instructional questions
    COMPARISON = "comparison"  # Comparison questions
    DEFINITION = "definition"  # Definition/what-is questions


class FAQSearchIntent(str, PyEnum):
    """FAQ search intent classification."""

    INFORMATIONAL = "informational"  # User seeking information
    NAVIGATIONAL = "navigational"  # User looking for specific page
    TRANSACTIONAL = "transactional"  # User ready to take action


class FAQStatus(str, PyEnum):
    """FAQ approval status."""

    DRAFT = "draft"  # AI-generated, not yet reviewed
    APPROVED = "approved"  # Reviewed and approved by user
    REJECTED = "rejected"  # Rejected by user
    PUBLISHED = "published"  # Published to article


class ArticleFAQ(Base):
    """AI-generated FAQ for article (optimized for AI search engines).

    Stores frequently asked questions and answers generated by the unified
    AI optimization service (v2.2). Optimized for Google AI Overviews and
    E-E-A-T compliance. Typically 3-5 FAQs per article.

    FAQs are:
    1. Embedded as JSON-LD Schema.org FAQPage markup (for SEO)
    2. Displayed as visible "常見問題" section at article bottom
    """

    __tablename__ = "article_faqs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Foreign key to articles
    article_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("articles.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Article this FAQ belongs to (one-to-many relationship)",
    )

    # ========================================================================
    # FAQ Content
    # ========================================================================
    question: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="FAQ question",
    )

    answer: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="FAQ answer (50-150 characters recommended)",
    )

    # ========================================================================
    # FAQ Classification
    # ========================================================================
    # Note: Using String instead of Enum to match varchar(20) column in database
    question_type: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="Type: factual, how_to, comparison, definition",
    )

    search_intent: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="Intent: informational, navigational, transactional",
    )

    # ========================================================================
    # Keywords and Relevance
    # ========================================================================
    # Format: ["keyword1", "keyword2", ...]
    keywords_covered: Mapped[list[str] | None] = mapped_column(
        ARRAY(Text),
        nullable=True,
        comment="Keywords naturally covered in this FAQ",
    )

    # AI confidence score (0.00 to 1.00)
    confidence: Mapped[float | None] = mapped_column(
        DECIMAL(precision=3, scale=2),
        nullable=True,
        comment="AI confidence score for this FAQ (0.00-1.00)",
    )

    # YMYL safety warning flag (for health/medical content)
    safety_warning: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default="false",
        comment="Whether this FAQ contains health/safety warnings (YMYL compliance)",
    )

    # ========================================================================
    # Position and Status
    # ========================================================================
    position: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        server_default="0",
        comment="Display order (0-based index)",
    )

    # Note: Using String instead of Enum to match varchar(20) column in database
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        server_default="'draft'",
        index=True,
        comment="Status: draft, approved, rejected, published",
    )

    # ========================================================================
    # Metadata
    # ========================================================================
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP,
        nullable=False,
        server_default="NOW()",
        comment="When this FAQ was created",
    )

    # Relationships
    article: Mapped["Article"] = relationship(
        "Article",
        back_populates="faqs",
    )

    def __repr__(self) -> str:
        """String representation."""
        q_preview = self.question[:50] + "..." if len(self.question) > 50 else self.question
        return f"<ArticleFAQ(id={self.id}, article_id={self.article_id}, question='{q_preview}', status={self.status})>"
