"""SEO suggestions model for Phase 7 unified AI optimization."""

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    ForeignKey,
    Integer,
    String,
    Text,
    TIMESTAMP,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base

if TYPE_CHECKING:
    from src.models.article import Article


class SEOSuggestion(Base):
    """AI-generated SEO optimization suggestions for articles.

    Stores SEO keywords (focus/primary/secondary), optimized meta description,
    and tags recommendations generated by the unified AI optimization service.
    """

    __tablename__ = "seo_suggestions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Foreign key to articles
    article_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("articles.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
        comment="Article for which SEO suggestions were generated (one-to-one relationship)",
    )

    # ========================================================================
    # Focus Keyword (Primary SEO keyword)
    # ========================================================================
    focus_keyword: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
        index=True,
        comment="Primary SEO keyword (1)",
    )

    focus_keyword_rationale: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="AI explanation for why this focus keyword was chosen",
    )

    # ========================================================================
    # Primary and Secondary Keywords
    # ========================================================================
    # Format: ["keyword1", "keyword2", "keyword3"]
    primary_keywords: Mapped[list[str] | None] = mapped_column(
        ARRAY(Text),
        nullable=True,
        comment="Primary keywords (3-5)",
    )

    # Format: ["long-tail-keyword1", "long-tail-keyword2", ...]
    secondary_keywords: Mapped[list[str] | None] = mapped_column(
        ARRAY(Text),
        nullable=True,
        comment="Secondary keywords (5-10)",
    )

    # ========================================================================
    # Keyword Metrics (JSONB for flexibility)
    # ========================================================================
    # Format:
    # {
    #   "focus_keyword": 0.65,
    #   "average_difficulty": 0.52,
    #   "difficulty_breakdown": {"keyword1": 0.6, "keyword2": 0.7}
    # }
    keyword_difficulty: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Difficulty scores for keywords (0.0-1.0)",
    )

    # Format:
    # {
    #   "focus_keyword": "5000-10000/月",
    #   "primary_keywords_total": "15000-25000/月"
    # }
    search_volume_estimate: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Estimated search volume for keywords",
    )

    # ========================================================================
    # Meta Description
    # ========================================================================
    suggested_meta_description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="AI-optimized meta description (150-160 chars recommended)",
    )

    # Format: ["Improvement 1", "Improvement 2", ...]
    meta_description_improvements: Mapped[list[str] | None] = mapped_column(
        ARRAY(Text),
        nullable=True,
        comment="List of improvements made to meta description",
    )

    meta_description_score: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="Quality score for meta description (0-100)",
    )

    # ========================================================================
    # Tags Recommendations
    # ========================================================================
    # Format:
    # [
    #   {"tag": "人工智能", "relevance": 0.95, "type": "primary"},
    #   {"tag": "医疗AI", "relevance": 0.92, "type": "primary"},
    #   {"tag": "深度学习医疗应用", "relevance": 0.78, "type": "secondary"},
    #   ...
    # ]
    suggested_tags: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Array of suggested tags with relevance scores and types",
    )

    tag_strategy: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="AI strategy explanation for tag recommendations",
    )

    # ========================================================================
    # Metadata
    # ========================================================================
    generated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP,
        nullable=False,
        server_default="NOW()",
        comment="When these SEO suggestions were generated",
    )

    # Relationships
    article: Mapped["Article"] = relationship(
        "Article",
        back_populates="seo_suggestion",
        uselist=False,
    )

    def __repr__(self) -> str:
        """String representation."""
        focus = self.focus_keyword or "N/A"
        return f"<SEOSuggestion(id={self.id}, article_id={self.article_id}, focus_keyword='{focus}')>"
