"""Title suggestions model for Phase 7 unified AI optimization."""

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    ForeignKey,
    Integer,
    String,
    Text,
    TIMESTAMP,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base

if TYPE_CHECKING:
    from src.models.article import Article


class TitleSuggestion(Base):
    """AI-generated title optimization suggestions for articles.

    Stores title recommendations with 3-part structure (prefix/main/suffix)
    generated by the unified AI optimization service. Includes 2-3 optimization
    options with different types (data-driven, authority-backed, how-to, etc.)
    """

    __tablename__ = "title_suggestions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Foreign key to articles
    article_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("articles.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
        comment="Article for which suggestions were generated (one-to-one relationship)",
    )

    # Original title components
    original_title_prefix: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
        comment='Original title prefix (if exists), e.g., "深度解析"',
    )

    original_title_main: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        comment="Original main title",
    )

    original_title_suffix: Mapped[str | None] = mapped_column(
        String(200),
        nullable=True,
        comment='Original title suffix (if exists), e.g., "权威指南"',
    )

    # AI-generated suggestions (JSONB for flexibility)
    # Format:
    # [
    #   {
    #     "id": "option_1",
    #     "title_prefix": "深度解析",
    #     "title_main": "人工智能革新医疗诊断：准确率提升30%",
    #     "title_suffix": "权威指南",
    #     "full_title": "深度解析 | 人工智能革新医疗诊断：准确率提升30% | 权威指南",
    #     "score": 95,
    #     "strengths": ["Contains specific data (30%)", "Compelling action words"],
    #     "type": "data_driven",
    #     "recommendation": "Best option for click-through rate",
    #     "character_count": {
    #       "prefix": 4,
    #       "main": 22,
    #       "suffix": 4,
    #       "total": 34
    #     }
    #   },
    #   ...  # 1-2 more options
    # ]
    suggested_title_sets: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Array of 2-3 title optimization options with scores and types",
    )

    # Optimization notes from AI
    # Format: ["注意事项1", "注意事项2", ...]
    optimization_notes: Mapped[list[str] | None] = mapped_column(
        ARRAY(Text),
        nullable=True,
        comment="General optimization notes from AI",
    )

    # Metadata
    generated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP,
        nullable=False,
        server_default="NOW()",
        comment="When these suggestions were generated",
    )

    generated_by: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        server_default="'unified_optimization_service'",
        comment="Service or user who generated suggestions",
    )

    # Relationships
    article: Mapped["Article"] = relationship(
        "Article",
        back_populates="title_suggestion",
        uselist=False,
    )

    def __repr__(self) -> str:
        """String representation."""
        return f"<TitleSuggestion(id={self.id}, article_id={self.article_id}, generated_at={self.generated_at})>"
