# =============================================================================
# Computer Use 自然语言指令模板
# =============================================================================
# 用于 Anthropic Computer Use API，使用繁体中文描述操作步骤
# 支持变量替换：{{ variable_name }}
# =============================================================================

# ==================== 登录相关 ====================

login_to_wordpress: |
  在登入頁面找到標籤為『使用者名稱或電子郵件』的文字輸入框。
  在此輸入框中輸入：『{{ username }}』。
  找到標籤為『密碼』的密碼輸入框。
  在此輸入框中輸入：『{{ password }}』。
  找到標籤為『登入』的按鈕，點擊它。
  等待頁面載入完成，確認已進入 WordPress 後台控制台。

# ==================== 導航相關 ====================

navigate_to_new_post: |
  找到左側選單中帶有圖釘圖示且標籤為『文章』的項目，點擊它。
  在展開的子選單中,找到並點擊標籤為『新增文章』的連結。
  等待頁面載入完成，確認頁面頂部出現文字『新增文章』。

navigate_to_posts_list: |
  找到左側選單中標籤為『文章』的項目，點擊它。
  在展開的子選單中，點擊標籤為『全部文章』的連結。
  等待頁面載入完成，確認頁面頂部出現『文章』標題和文章列表。

# ==================== 內容編輯 ====================

fill_title: |
  找到標籤為『新增標題』或 ID 為 'title' 的大型文字輸入框。
  在此輸入框中輸入以下文字：『{{ value }}』。
  確認輸入框中已顯示輸入的標題文字。

fill_content: |
  找到主要內容編輯器右上方的『文字』(Text) 分頁標籤，點擊它。
  在主要內容編輯器的大型文字區域中，清空原有內容。
  在文字區域中貼上以下內容：
  ---
  {{ content }}
  ---
  確認文字區域中已顯示貼上的內容。

clean_html_entities: |
  在『文字』編輯模式的內容區域中，查找並刪除所有的『&nbsp;』字串。
  如果有其他多餘的 HTML 標籤或實體字符（例如 &lt; &gt; &amp;），也一併清理。
  確認內容已清理完成，沒有多餘的 HTML 實體。

switch_to_visual_mode: |
  找到主要內容編輯器右上方的『視覺化』(Visual) 分頁標籤，點擊它。
  確認編輯器已切換到視覺化編輯模式。

# ==================== 媒體庫與圖片 ====================

open_media_library: |
  找到主要內容編輯器左上方的標籤為『新增媒體』的按鈕，點擊它。
  等待一個標題為『插入媒體』或『新增媒體』的彈出視窗出現。
  確認視窗已完全載入，顯示媒體庫內容。

upload_file: |
  在『插入媒體』視窗中，點擊標籤為『上傳檔案』的分頁。
  點擊標籤為『選擇檔案』的按鈕，在檔案選擇器中選擇圖片檔案『{{ file_path }}』。
  或者，直接將圖片檔案拖曳到標有『請將檔案拖曳到這裡上傳』的區域。
  等待檔案上傳完成，確認圖片縮圖出現在媒體庫中。

wait_for_upload_complete: |
  等待上傳進度條完成。
  確認圖片已成功上傳，媒體庫中出現新上傳的圖片縮圖。
  圖片應該自動被選中（有藍色邊框或高亮顯示）。

fill_image_metadata: |
  確保圖片已被選中（有藍色邊框）。
  在視窗右側的『附件詳細資料』或『附件詳情』區域：
  - 找到標籤為『替代文字』或『Alt Text』的輸入框，填入：『{{ alt }}』。
  - 找到標籤為『標題』的輸入框，填入：『{{ title }}』。
  - 找到標籤為『說明』或『Caption』的文字區域，填入：『{{ caption }}』。
  - 如果有標籤為『關鍵字』的輸入框，填入：『{{ keywords }}』。
  - 如果有標籤為『攝影師』的輸入框，填入：『{{ photographer }}』。
  確認所有欄位都已填寫完成。

configure_image_display: |
  在視窗右側下方的『附件顯示設定』區域：
  - 找到標籤為『對齊』的下拉選單，選擇『{{ align }}』。
  - 找到標籤為『連結至』的下拉選單，選擇『{{ link_to }}』。
  - 找到標籤為『尺寸』的下拉選單，選擇『{{ size }}』。
  確認所有設定已選擇正確。

insert_image_to_content: |
  找到視窗右下角的標籤為『插入至文章』或『Insert into post』的按鈕，點擊它。
  確認彈出視窗已關閉，且圖片已出現在主要內容編輯器的游標位置。

# ==================== 特色圖片 ====================

set_as_featured_image: |
  找到頁面右側標題為『特色圖片』的區塊。
  點擊該區塊內標籤為『設定特色圖片』的連結或按鈕。
  等待一個類似『插入媒體』的彈出視窗出現。

select_featured_image_from_library: |
  在『特色圖片』視窗中，點擊標籤為『媒體庫』的分頁。
  在媒體庫中找到目標圖片（{{ image_name }}），點擊選中它。
  確認圖片被選中（有藍色邊框或高亮顯示）。

confirm_featured_image: |
  確保目標圖片已被選中。
  找到視窗右下角的標籤為『設定特色圖片』的按鈕，點擊它。
  等待視窗關閉。
  確認頁面右側『特色圖片』區塊已顯示選中的圖片縮圖。

edit_image: |
  在圖片預覽下方，找到並點擊標籤為『編輯圖片』或『Edit Image』的連結。
  等待進入圖片編輯介面。

crop_image: |
  在圖片編輯介面右側，找到標籤為『縮圖設定』或類似名稱的區塊。
  找到標籤為『{{ size_name }}』的選項（例如『縮圖』、『中』、『大』），點擊它。
  調整圖片上出現的裁切框，確保主要內容（例如人物面部、重要元素）完整出現在框內。
  點擊裁切按鈕（通常是一個方形或剪刀圖示）。

save_crop: |
  找到標籤為『儲存』或『更新』的按鈕，點擊它。
  等待裁切操作完成並保存。
  確認頁面顯示『圖片已更新』或類似訊息。

# ==================== 分類與標籤 ====================

add_tag: |
  找到頁面右側標題為『標籤』的區塊。
  找到該區塊內標籤為『新增標籤』或『Add New Tag』的文字輸入框。
  在此輸入框中輸入標籤文字：『{{ tag }}』。
  點擊輸入框旁邊標籤為『新增』的按鈕，或按下 Enter 鍵。
  確認輸入的標籤已出現在輸入框下方或標籤列表中。

remove_tag: |
  找到頁面右側『標籤』區塊中的標籤列表。
  找到標籤『{{ tag }}』，點擊它旁邊的 X 按鈕或刪除圖示。
  確認該標籤已從列表中移除。

select_category: |
  找到頁面右側標題為『分類』的區塊。
  在分類列表中，找到並勾選名稱為『{{ category }}』的核取方塊。
  確認該分類旁邊的核取方塊已被勾選（打勾狀態）。

unselect_category: |
  找到頁面右側『分類』區塊的分類列表。
  找到名稱為『{{ category }}』的核取方塊，如果已勾選，則取消勾選。
  確認該分類旁邊的核取方塊已變為未勾選狀態。

# ==================== SEO 配置 (Yoast SEO) ====================

configure_seo_plugin: |
  向下滾動頁面，找到標題包含『Yoast SEO』或『SEO』的區塊。
  如果區塊是折疊的，點擊展開它。
  在 SEO 區塊中：
  - 找到標籤為『焦點關鍵字』或『Focus Keyword』的輸入框，填入：『{{ focus_keyword }}』。
  - 找到標籤為『SEO 標題』或『SEO Title』的輸入框（可能需要點擊『編輯摘要』按鈕才出現），填入：『{{ meta_title }}』。
  - 找到標籤為『Meta 描述』或『Meta Description』的文字區域，填入：『{{ meta_description }}』。
  確認各欄位已填入內容。

expand_seo_section: |
  向下滾動頁面，找到標題包含『Yoast SEO』的區塊。
  如果該區塊是折疊的（只顯示標題），點擊標題展開區塊。
  確認 SEO 編輯欄位已顯示出來。

# ==================== 發布相關 ====================

click_save_draft: |
  找到頁面右上角『發表』區塊中的標籤為『儲存為草稿』或『Save Draft』的按鈕，點擊它。
  等待頁面刷新或顯示提示訊息『文章草稿已更新』或類似內容。

click_publish: |
  找到頁面右上角『發表』區塊中藍色的『發表』或『Publish』按鈕，點擊它。
  等待頁面刷新或顯示提示訊息『文章已發佈』或類似內容。

schedule_publish: |
  找到頁面右上角『發表』區塊。
  點擊『立即發表』旁邊的『編輯』或『Edit』連結。
  在彈出的日期時間選擇器中：
  - 選擇月份：{{ month }}
  - 選擇日期：{{ day }}
  - 選擇年份：{{ year }}
  - 選擇小時：{{ hour }}
  - 選擇分鐘：{{ minute }}
  點擊『確定』或『OK』按鈕。
  點擊現在標籤為『排程』或『Schedule』的按鈕（原本的『發表』按鈕）。
  等待頁面顯示『文章已排程』或類似訊息。

click_preview: |
  找到頁面右上角『發表』區塊中的標籤為『預覽』或『Preview』的按鈕，點擊它。
  等待預覽頁面在新視窗或新分頁中開啟。

# ==================== 驗證相關 ====================

verify_login_success: |
  確認頁面 URL 包含 '/wp-admin'。
  確認頁面左側出現 WordPress 管理選單。
  確認頁面頂部出現帶有 WordPress 標誌的管理工具列。

verify_post_created: |
  確認頁面 URL 包含 '/post.php' 和 'action=edit'。
  確認頁面頂部出現『編輯文章』或文章標題。
  確認頁面右上角出現『發表』區塊。

verify_media_uploaded: |
  確認媒體庫中出現剛上傳的圖片縮圖。
  確認圖片旁邊沒有顯示錯誤訊息。
  確認圖片可以被選中（點擊後有藍色邊框）。

verify_publish_success: |
  確認頁面頂部出現綠色的成功訊息，內容類似『文章已發佈』。
  確認頁面 URL 已更新（可能重定向到文章編輯頁面）。
  確認『發表』按鈕變為『更新』按鈕。

# ==================== 錯誤處理 ====================

dismiss_notification: |
  檢查頁面頂部是否有通知欄（通常是黃色或藍色背景）。
  如果有通知欄，找到關閉按鈕（通常是 X 圖示），點擊它。
  確認通知欄已消失。

handle_conflict_warning: |
  如果頁面顯示『另一個使用者正在編輯此文章』或類似警告訊息。
  找到標籤為『接管』或『Take Over』的按鈕，點擊它。
  確認警告消失，可以繼續編輯。

retry_on_timeout: |
  如果操作超時或頁面無回應，等待 5 秒。
  重新整理頁面（按 F5 或點擊瀏覽器重新整理按鈕）。
  重新執行上一個操作。
