# WordPress 后台选择器配置 (繁体中文界面)
# 支持多选择器（优先级从上到下）
# Phase 2: Playwright Provider 使用

# ==================== 登录 ====================
login_username:
  - "#user_login"
  - "input[name='log']"

login_password:
  - "#user_pass"
  - "input[name='pwd']"

login_button:
  - "#wp-submit"
  - "input[type='submit'][name='wp-submit']"

dashboard:
  - "#dashboard-widgets"
  - "#wpbody-content"
  - ".wrap h1:has-text('儀表板')"

# ==================== 菜单导航 ====================
menu_posts:
  - "#menu-posts > a"
  - "a[href='edit.php']"

menu_new_post:
  - "#menu-posts ul > li > a:has-text('新增文章')"
  - "a[href='post-new.php']"

# ==================== 文章编辑器 ====================
new_post_title:
  - "#title"
  - "input[name='post_title']"

content_text_mode_button:
  - "#content-html"
  - "a.wp-switch-editor[data-mode='html']"

content_visual_mode_button:
  - "#content-tmce"
  - "a.wp-switch-editor[data-mode='tmce']"

content_textarea:
  - "#content"
  - "textarea[name='content']"

content_iframe:
  - "#content_ifr"
  - "iframe.wp-editor-area"

# ==================== 按钮 ====================
save_draft:
  - "#save-post"
  - "input[name='save']"

publish:
  - "#publish"
  - "input[name='publish']"

preview:
  - "#post-preview"
  - "a#preview-action"

# ==================== 媒体库 ====================
add_media_button:
  - "#insert-media-button"
  - "button.insert-media"

media_modal:
  - ".media-modal"
  - ".media-frame"

upload_files_tab:
  - "button:has-text('上傳檔案')"
  - ".media-menu-item:has-text('上傳檔案')"
  - ".media-router button:first-child"

select_files_button:
  - "button:has-text('選擇檔案')"
  - ".browser button.button"

media_attachment:
  - ".media-modal .attachment"
  - "li.attachment"

attachment_details:
  - ".media-sidebar"
  - ".attachment-details"

# 图片元数据字段
image_alt:
  - ".media-modal .setting[data-setting='alt'] input"
  - "input[aria-describedby='alt-text-description']"
  - "input[id*='alt-text']"

image_title:
  - ".media-modal .setting[data-setting='title'] input"
  - "input[data-setting='title']"
  - "input[id*='attachment-title']"

image_caption:
  - ".media-modal .setting[data-setting='caption'] textarea"
  - "textarea[data-setting='caption']"
  - "textarea[id*='attachment-caption']"

image_description:
  - ".media-modal .setting[data-setting='description'] textarea"
  - "textarea[id*='attachment-description']"

# 图片显示设置
image_align_select:
  - ".media-modal .setting[data-setting='align'] select"
  - "select[data-setting='align']"

image_link_select:
  - ".media-modal .setting[data-setting='link'] select"
  - "select[data-setting='link']"

image_size_select:
  - ".media-modal .setting[data-setting='size'] select"
  - "select[data-setting='size']"

insert_into_post_button:
  - ".media-modal button.media-button-insert"
  - "button:has-text('插入至文章')"
  - ".media-toolbar-primary button.media-button-insert"

media_modal_close:
  - ".media-modal button.media-modal-close"
  - "button[aria-label='關閉']"

# ==================== 特色图片 ====================
set_featured_image_link:
  - "#set-post-thumbnail"
  - "a:has-text('設定特色圖片')"

set_featured_image_button:
  - ".media-modal button.media-button-select"
  - "button:has-text('設定特色圖片')"

featured_image_thumbnail:
  - "#postimagediv .inside img"
  - "#set-post-thumbnail img"

remove_featured_image_link:
  - "#remove-post-thumbnail"
  - "a:has-text('移除特色圖片')"

edit_image_link:
  - ".media-modal a.edit-attachment"
  - "button:has-text('編輯圖片')"

image_editor:
  - "#image-preview"
  - ".imgedit-wrap"

crop_button:
  - "button[aria-label='裁切']"
  - ".imgedit-crop-wrap button"

save_crop_button:
  - "input[value='儲存']"
  - ".imgedit-submit-btn"
  - "button:has-text('儲存')"

# ==================== 标签和分类 ====================
new_tag_input:
  - "#new-tag-post_tag"
  - "input.newtag"

add_tag_button:
  - ".tagsdiv input.button"
  - "input.button.tagadd"

tag_checklist:
  - ".tagchecklist"

category_checklist:
  - "#categorychecklist"

# ==================== SEO 插件（Yoast SEO） ====================
yoast_section:
  - "#wpseo_meta"
  - ".yoast-seo-metabox"

yoast_focus_keyword:
  - "#yoast_wpseo_focuskw"
  - "#focus-keyword-input-metabox"
  - "input[name='yoast_wpseo_focuskw']"

yoast_edit_snippet:
  - ".snippet-editor__button"
  - "button:has-text('編輯摘要')"

yoast_meta_title:
  - "#yoast-google-preview-title-metabox"
  - "input[name='yoast_wpseo_title']"
  - "#snippet-editor-title"

yoast_meta_description:
  - "#yoast-google-preview-description-metabox"
  - "textarea[name='yoast_wpseo_metadesc']"
  - "#snippet-editor-meta-description"

yoast_score_indicator:
  - ".wpseo-score-icon"

# ==================== 发布时间 ====================
edit_timestamp_link:
  - "a.edit-timestamp"
  - "a[href='#edit_timestamp']"

publish_month:
  - "#mm"
  - "select[name='mm']"

publish_day:
  - "#jj"
  - "input[name='jj']"

publish_year:
  - "#aa"
  - "input[name='aa']"

publish_hour:
  - "#hh"
  - "input[name='hh']"

publish_minute:
  - "#mn"
  - "input[name='mn']"

save_timestamp_link:
  - "a.save-timestamp"
  - "button:has-text('確定')"

# ==================== 消息提示 ====================
success_message:
  - "#message.updated"
  - ".notice.notice-success"
  - ".updated.notice"

error_message:
  - "#message.error"
  - ".notice.notice-error"
  - ".error.notice"

# 具体成功消息
draft_saved_message:
  - "#message:has-text('草稿已更新')"

post_published_message:
  - "#message:has-text('文章已發佈')"

post_scheduled_message:
  - "#message:has-text('文章已排程')"

# ==================== 文章发布后 ====================
post_permalink:
  - "#sample-permalink a"
  - ".edit-post-post-link__link"

view_post_link:
  - "#message a:has-text('檢視文章')"
  - ".notice a[href*='p=']"

# ==================== 其他元素 ====================
loading_indicator:
  - ".spinner.is-active"
  - ".components-spinner"

ajax_loading:
  - "#ajax-loading"
  - ".loading"

# 媒体上传进度
upload_progress:
  - ".media-uploader-status"
  - ".upload-progress"

# 编辑器加载完成
editor_loaded:
  - "#content"
  - "#title"

# 页面加载完成
page_loaded:
  - "#wpbody"
  - "#wpadminbar"
