"""API schemas for request/response validation."""

from src.api.schemas.analytics import (
    CostUsageEntry,
    ProviderMetric,
    RecommendationsResponse,
    StorageUsageEntry,
)
from src.api.schemas.base import (
    BaseSchema,
    ErrorResponse,
    PaginatedResponse,
    PaginationParams,
    SuccessResponse,
    TimestampSchema,
)
from src.api.schemas.monitoring import ExecutionLogEntry, TaskFilters, TaskStatistics
from src.api.schemas.optimization import (
    FAQData,
    GenerateOptimizationsRequest,
    GenerationMetadata,
    MetaDescriptionData,
    OptimizationError,
    OptimizationOptions,
    OptimizationStatusResponse,
    OptimizationsResponse,
    SEOKeywordsData,
    SEOSuggestionsData,
    TagsData,
    TitleSuggestionsData,
)
from src.api.schemas.proofreading import (
    ArticleSummary,
    BatchDecisionsPayload,
    BatchDecisionsResponse,
    DecisionPayload,
    ProcessingMetadataSchema,
    ProofreadingIssueDetail,
    ProofreadingIssueSchema,
    ProofreadingPosition,
    ProofreadingResponse,
    ProofreadingReviewStats,
    ProofreadingStatisticsSchema,
    ReviewDecisionsPayload,
    ReviewDecisionsResponse,
    SavedDecisionSummary,
    WorklistItemSummary,
)
from src.api.schemas.publishing import (
    PublishOptions,
    PublishRequest,
    PublishResult,
    PublishTaskResponse,
    Screenshot,
)
from src.api.schemas.settings import (
    ConnectionTestRequest,
    ConnectionTestResponse,
    SettingsResponse,
    SettingsUpdateRequest,
)
from src.api.schemas.worklist import (
    WorklistItemDetailResponse,
    WorklistItemResponse,
    WorklistStatisticsResponse,
    WorklistStatusHistoryEntry,
    WorklistStatusUpdateRequest,
    WorklistSyncStatusResponse,
    WorklistSyncTriggerResponse,
)

__all__ = [
    "BaseSchema",
    "TimestampSchema",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorResponse",
    "SuccessResponse",
    "ProofreadingIssueSchema",
    "ProofreadingStatisticsSchema",
    "ProcessingMetadataSchema",
    "ProofreadingResponse",
    "ProofreadingIssueDetail",
    "ProofreadingReviewStats",
    "ProofreadingPosition",
    "DecisionPayload",
    "ReviewDecisionsPayload",
    "ReviewDecisionsResponse",
    "WorklistItemSummary",
    "ArticleSummary",
    "BatchDecisionsPayload",
    "BatchDecisionsResponse",
    "SavedDecisionSummary",
    "PublishOptions",
    "PublishRequest",
    "PublishResult",
    "PublishTaskResponse",
    "Screenshot",
    "TaskFilters",
    "TaskStatistics",
    "ExecutionLogEntry",
    "ProviderMetric",
    "CostUsageEntry",
    "StorageUsageEntry",
    "RecommendationsResponse",
    "SettingsResponse",
    "SettingsUpdateRequest",
    "ConnectionTestRequest",
    "ConnectionTestResponse",
    "WorklistItemDetailResponse",
    "WorklistItemResponse",
    "WorklistStatisticsResponse",
    "WorklistStatusHistoryEntry",
    "WorklistSyncStatusResponse",
    "WorklistStatusUpdateRequest",
    "WorklistSyncTriggerResponse",
    # Optimization schemas (Phase 7 - Unified AI Optimization)
    "GenerateOptimizationsRequest",
    "OptimizationOptions",
    "OptimizationsResponse",
    "TitleSuggestionsData",
    "SEOSuggestionsData",
    "SEOKeywordsData",
    "MetaDescriptionData",
    "TagsData",
    "FAQData",
    "GenerationMetadata",
    "OptimizationStatusResponse",
    "OptimizationError",
]
